defmodule OrderSystem.Search.Orders do
  @moduledoc """
  Elasticsearch repository for the `OrderSystem.Search.Order` read model.

  Generated by `Orkestra.ES.Repository`, this module exposes an idiomatic,
  tuple-returning API over the `orders` index: `get/2`, `save/2`, `save_all/2`,
  `delete/2`, `count/2`, `stream/1`, `refresh/1`, the raw `search/2` escape
  hatch, and the paginated/faceted `get_paged/1`.

  See `OrderSystem.Orders.Queries` for ready-made query examples built on top of
  this repository.
  """
  use Orkestra.ES.Repository,
    schema: OrderSystem.Search.Order,
    cluster: OrderSystem.ESCluster
end
