if Code.ensure_loaded?(Ecto.Migrator) do
  defmodule Mix.Tasks.Orkestra.Projection.Rollback do
    @shortdoc "Roll back migrations for a single Orkestra projection"
    @moduledoc """
    Rolls back migrations for the named projection.

    By default rolls back one step. Use `--step N` to roll back N steps,
    or `--all` to roll back every migration.

    The projection's migration directory and migration tracking table are
    discovered via `__projection_config__/0` on the projector module
    (generated by `use Orkestra.Projector`).

    ## Usage

        mix orkestra.projection.rollback MyApp.OrderProjector
        mix orkestra.projection.rollback MyApp.OrderProjector --step 3
        mix orkestra.projection.rollback MyApp.OrderProjector --all

    ## Options

    - `--step N` — number of migrations to roll back (default: 1).
    - `--all` — roll back all applied migrations.
    """

    use Mix.Task

    @impl Mix.Task
    def run(args) do
      {opts, positional, _} =
        OptionParser.parse(args, strict: [step: :integer, all: :boolean])

      case positional do
        [projector_module_str | _] ->
          Mix.Task.run("app.config")
          module = Module.concat([projector_module_str])
          config = module.__projection_config__()

          migrator_opts =
            if Keyword.get(opts, :all, false) do
              [all: true, migration_source: config.migration_source]
            else
              step = Keyword.get(opts, :step, 1)
              [step: step, migration_source: config.migration_source]
            end

          {:ok, _, _} =
            Ecto.Migrator.with_repo(config.repo, fn repo ->
              Ecto.Migrator.run(repo, config.migrations_path, :down, migrator_opts)
            end)

          Mix.shell().info("Rollback complete for #{config.projector_name}")

        [] ->
          Mix.raise(
            "mix orkestra.projection.rollback requires a projector module name\n\n" <>
              "Usage: mix orkestra.projection.rollback MyApp.OrderProjector"
          )
      end
    end
  end
end
