if Code.ensure_loaded?(Ecto.Migrator) do
  defmodule Mix.Tasks.Orkestra.Projection.Migrate do
    @shortdoc "Run migrations for a single Orkestra projection"
    @moduledoc """
    Runs all pending migrations for the named projection.

    The projection's migration directory and migration tracking table are
    discovered via `__projection_config__/0` on the projector module
    (generated by `use Orkestra.Projector`).

    ## Usage

        mix orkestra.projection.migrate MyApp.OrderProjector

    Each projection uses an isolated `migration_source` table so migrations
    for different projections never interfere with each other.
    """

    use Mix.Task

    @impl Mix.Task
    def run([projector_module_str | _rest]) do
      Mix.Task.run("app.config")
      module = Module.concat([projector_module_str])
      config = module.__projection_config__()

      {:ok, _, _} =
        Ecto.Migrator.with_repo(config.repo, fn repo ->
          Ecto.Migrator.run(repo, config.migrations_path, :up,
            all: true,
            migration_source: config.migration_source
          )
        end)

      Mix.shell().info("Migrations complete for #{config.projector_name}")
    end

    def run([]) do
      Mix.raise(
        "mix orkestra.projection.migrate requires a projector module name\n\n" <>
          "Usage: mix orkestra.projection.migrate MyApp.OrderProjector"
      )
    end
  end
end
