if Code.ensure_loaded?(Ecto.Migrator) do
  defmodule Mix.Tasks.Orkestra.Projection.Drop do
    @shortdoc "Drop all migrations and state for a single Orkestra projection"
    @moduledoc """
    Rolls back all migrations for the named projection and deletes its
    checkpoint and dead-letter rows.

    This is a destructive operation that removes all read-model tables
    and tracking state for the projection. The projection can be
    re-created by running `mix orkestra.projection.migrate` again, or
    a full rebuild can be done with `mix orkestra.projection.rebuild`.

    The projection's repo, migration directory, and tracking table are
    discovered via `__projection_config__/0` on the projector module
    (generated by `use Orkestra.Projector`).

    ## Usage

        mix orkestra.projection.drop MyApp.OrderProjector

    ## What this does

    1. Rolls back ALL applied migrations for the named projection.
    2. Deletes the checkpoint row for this projector (avoids orphaned state
       that would cause the projector to skip replay on next start).
    3. Deletes all dead-letter rows for this projector.
    """

    use Mix.Task

    import Ecto.Query, only: [from: 2]

    alias Orkestra.Projection.Checkpoint
    alias Orkestra.Projection.DeadLetter

    @impl Mix.Task
    def run([projector_module_str | _rest]) do
      Mix.Task.run("app.config")
      module = Module.concat([projector_module_str])
      config = module.__projection_config__()

      {:ok, _, _} =
        Ecto.Migrator.with_repo(config.repo, fn repo ->
          # Step 1: Roll back all migrations
          Ecto.Migrator.run(repo, config.migrations_path, :down,
            all: true,
            migration_source: config.migration_source
          )

          # Step 2: Delete checkpoint row — prevents orphaned checkpoint that
          # would cause the projector to skip replay on next start (Pitfall 6).
          repo.delete_all(
            from(c in Checkpoint, where: c.projector_name == ^config.projector_name)
          )

          # Step 3: Delete dead-letter rows for this projection
          repo.delete_all(
            from(d in DeadLetter, where: d.projector_name == ^config.projector_name)
          )
        end)

      Mix.shell().info("Drop complete for #{config.projector_name}")
    end

    def run([]) do
      Mix.raise(
        "mix orkestra.projection.drop requires a projector module name\n\n" <>
          "Usage: mix orkestra.projection.drop MyApp.OrderProjector"
      )
    end
  end
end
